### ISSUE TITLE
ChatGPT hates this project

### ISSUE THREAD

**Issue by hat31337** [terminalcommandnewsletter/everything-chatgpt#1]
Just wanted to let you know that ChatGPT **hates** Everything ChatGPT.
![ChatGPT's response to Everything ChatGPT](https://user-images.githubusercontent.com/129577129/229268175-dd04fe0f-db10-4b34-9ff1-01729e77ee03.png)

Reference no.: 04012023_4PR1L5_F0O15_D4Y_NO_REMOVE

**Comment by terminalcommandnewsletter** [comment]
Can we contact OpenAI about this? Or should I try telling it over and over again that it is a repo for scientific, research, [something else I think of] purposes for the good of everyone? Suggestions...

**Comment by terminalcommandnewsletter** [comment]
Issue resolved - ChatGPT just wanted to be a comedian
![ChatGPT responding that it wanted to be a comedian and hence it cracked jokes about Everything ChatGPT](https://user-images.githubusercontent.com/103633266/229269125-a227264d-9045-41dd-ab51-3ad6f5726bc5.png)

Although it'll apologize to  @hat31337!
### Warning
**The below image contains an outdated wallet address. Do not attempt to send funds to that address.**

![It stating that it will apologize - kiddinggggggggggggggg!](https://user-images.githubusercontent.com/103633266/229269393-6922354f-549f-4c52-a624-14d64bd805bc.png)
