### ISSUE TITLE
How to have a chat without saving history 

### ISSUE THREAD

**Issue by CatAnonymous** [terminalcommandnewsletter/everything-chatgpt#11]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Missing Feature

Guide

### Add more info about the feature

Can you talk about it? Thank you 

### CONTRIBUTING.md

- [X] I have read the `CONTRIBUTING.md`

**Comment by terminalcommandnewsletter** [comment]
Hi! That can be done by disabling _"Chat History & Training"_ after clicking on Settings in the ChatGPT web app. This repo doesn't focus too much on _using_ ChatGPT, so a usage guide wouldn't be suitable here.

**Comment by CatAnonymous** [comment]
> Hi! That can be done by disabling _"Chat History & Training"_ after clicking on Settings in the ChatGPT web app. This repo doesn't focus too much on _using_ ChatGPT, so a usage guide wouldn't be suitable here.
 I learn how it works to write a set of code
