### ISSUE TITLE
API about conversation/gen_title 

### ISSUE THREAD

**Issue by progratient** [terminalcommandnewsletter/everything-chatgpt#2]
**Hi,  may i ask what the official's prompt for conversation titile generation ?**
I designed a prompt but not ideable, not as good as official's. Below is my prompt for generating conversation title:

> Please generate a short and concise chat topic based on the following chat content and language, words length should be around 3 to 10, don't try to reply chat content, if there is no specific topic, return the topic of "Casual chat". the generated topic text language must be the same as the chat's lauguage. for example："hello"，the topic should be "greeting" and "haha" is "Casual chat".  

Thank u.

**Comment by terminalcommandnewsletter** [comment]
That isn't visible via ChatGPT's backend API and prompt engineering isn't currently the purpose of this repo, hence this issue is being closed.
