### ISSUE TITLE
Calling JS function

### ISSUE THREAD

**Issue by Hokyjack** [terminalcommandnewsletter/everything-chatgpt#3]
Hey, this is very cool repo, thumbs up for your hard work!
I have a question - is it possible to call the javascript function for example getConversations using the Chrome console? It seems the functions are linked to "e" some event? Is there a way to call it directly?

Also, they've added a copy button next to Thumbup/Thumbdown buttons, I'm curious how this function extracts the markdown to the raw format (non-html text).

**Comment by terminalcommandnewsletter** [comment]
Thanks for the appreciation.
1. I can't find a way of running these functions, although there may be another method.
2. It just copies the raw Markdown. Although, if you select the text, copy and paste it into LibreOffice Writer, Google Docs, etc., formatting is retained (with some formatting like code dependent on the program, but generally a monospace font)
Hope that answers your question.
