### ISSUE TITLE
Feature not covered: API: GET /backend-api/settings/beta_features

### ISSUE THREAD

**Issue by 0xdevalias** [terminalcommandnewsletter/everything-chatgpt#7]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Missing Feature

API: GET /backend-api/settings/beta_features

### Add more info about the feature

**Request:**

```
GET https://chat.openai.com/backend-api/settings/beta_features
```

**Response:**

```json
{"browsing":false,"code_interpreter":false,"plugins":true}
```

### Optionally, add more information

You can find a full listing/reference to all of my ChatGPT insights/deepdives/etc here:

- https://gist.github.com/0xdevalias/4ac297ee3f794c17d0997b4673a2f160

### CONTRIBUTING.md

- [X] I have read the `CONTRIBUTING.md`

**Comment by terminalcommandnewsletter** [comment]
I noticed the announcement about beta features, but don't use ChatGPT Plus for me document this feature. Since you've provided me request details, I may add those to the repo (with attribution, of course)

**Comment by 0xdevalias** [comment]
That makes sense. Sounds good.

You can see the `/settings/beta_features` API endpoints mentioned in this chunk:

- https://chat.openai.com/_next/static/chunks/pages/_app-ab949dad0ea9d6e3.js

```js
(U.setUserSettingsBetaFeature = function (U, B, G) {
  var Y = new URLSearchParams({ feature: B, value: G.toString() });
  return this.fetch(
    "".concat(ty, "/settings/beta_features?").concat(Y),
    { method: "POST", headers: (0, Z._)({}, this.getAuthHeader(U)) }
  );
}),
(U.getUserSettingBetaFeatures = function (U) {
  return this.fetch("".concat(ty, "/settings/beta_features"), {
    method: "GET",
    headers: (0, Z._)(
      { "Content-Type": "application/json" },
      this.getAuthHeader(U)
    ),
  });
}),
```

**Comment by terminalcommandnewsletter** [comment]
Hi! Using a Plus account, this is the response received. I'll add that to the repo and close this issue.

```
{browsing: false, chat_preferences: true, code_interpreter: true, plugins: true}
```

**Comment by terminalcommandnewsletter** [comment]
I've added this to the repo in commit ccd25dd!
