### ISSUE TITLE
Section out-of-date: User Data - GET /backend-api/accounts/check

### ISSUE THREAD

**Issue by 0xdevalias** [terminalcommandnewsletter/everything-chatgpt#9]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Out-of-date Section

User Data - /backend-api/accounts/check

### Incorrect info

In the 'User Data' section, the details about the `/backend-api/accounts/check` endpoint are outdated/incomplete:

- https://github.com/terminalcommandnewsletter/everything-chatgpt#user-data

### Optionally, provide the correct info

**Request:**

```
GET https://chat.openai.com/backend-api/accounts/check
```

**Response (prettified):**

```json
{
    "account_plan":
    {
        "is_paid_subscription_active": true,
        "subscription_plan": "chatgptplusplan",
        "account_user_role": "account-owner",
        "was_paid_customer": true,
        "has_customer_object": true,
        "subscription_expires_at_timestamp": 1234567890
    },
    "user_country": "XX",
    "features":
    [
        "plugins_available",
        "tools3_dev",
        "dfw_message_feedback",
        "new_model_switcher_20230512",
        "data_controls_enabled",
        "show_existing_user_age_confirmation_modal",
        "tools3",
        "model_switcher",
        "infinite_scroll_history",
        "data_deletion_enabled",
        "dfw_inline_message_regen_comparison",
        "model_preview",
        "browsing_available",
        "data_export_enabled",
        "log_statsig_events",
        "beta_features",
        "log_intercom_events"
    ]
}
```

### Optionally, add more information

You can find a full listing/reference to all of my ChatGPT insights/deepdives/etc here:

- https://gist.github.com/0xdevalias/4ac297ee3f794c17d0997b4673a2f160

### CONTRIBUTING.md

- [X] I have read the `CONTRIBUTING.md`

**Comment by terminalcommandnewsletter** [comment]
Is just the `subscription_expires_at_timestamp` and `features` that are out-of-date or is it also something else?

**Comment by terminalcommandnewsletter** [comment]
I have added the changes to the repo.
